migration_tools/migration_tasks/batch_poster.py

Otherwise causes error when using the `BatchPoster` within Airflow.

Adds use_logging parameter to BatchPoster

---

src/folio_migration_tools/library_configuration.py
src/folio_migration_tools/mapper_base.py
src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
tests/test_mapping_file_mapper_base.py
tests/test_user_transformer.py

See tests. 
For object arrays, like Notes, electronicAccess, fields containing a delimiter will be split into multiple objects.
For string arrays, multiple values will be added.

generate multiple values/objects for data with delimiters. closes #183

---

CONTRIBUTING.md
tests/test_rules_mapper_holdings.py

Apologies for the extra commits in this branch -- they were related to issue 218 and had already been merged in.
The real changes are in tests/test_rules_mapper_holdings.py

closes #347 increase test coverage in srcfolio migration toolsmarc rules transformationrules mapper holdingspy

---

src/folio_migration_tools/migration_tasks/batch_poster.py

A minor tweak in service of handling single-record API types. Refactored to generalize existing handling for authorities to any type that doesn't have a batch API:
- Replaced `post_authorities method` with `post_single_records`
- Added a `"is_batch"` attribute to `list_objects` `"choices"` objects

Refactored BatchPoster to generalize handling record types that do not support batch loading APIs (eg. Authorities and Organizations)

---

README.md
src/folio_migration_tools/mapping_file_transformation/user_mapper.py
src/folio_migration_tools/migration_tasks/user_transformer.py
tests/test_user_mapper.py

Small tweaks to the user mapper and user transformer tasks to avoid creating objects or adding fields to the generated user record that can cause problems when reloading users without clearing existing data. Closes #469.

469 remove extraneous fields from user objects created by usermapper

---

src/fetch_default_ref_data.py
src/folio_migration_tools/extradata_writer.py
src/folio_migration_tools/holdings_helper.py
src/folio_migration_tools/mapper_base.py
src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
src/folio_migration_tools/mapping_file_transformation/mapping_file_mapping_base_impl.py
src/folio_migration_tools/mapping_file_transformation/notes_mapper.py
src/folio_migration_tools/mapping_file_transformation/organization_mapper.py
src/folio_migration_tools/marc_rules_transformation/conditions.py
src/folio_migration_tools/marc_rules_transformation/hrid_handler.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
src/folio_migration_tools/migration_tasks/bibs_transformer.py
src/folio_migration_tools/migration_tasks/migration_task_base.py
src/folio_migration_tools/migration_tasks/organization_transformer.py
src/folio_migration_tools/migration_tasks/requests_migrator.py
src/folio_migration_tools/migration_tasks/reserves_migrator.py
src/folio_migration_tools/report_blurbs.py
tests/test_batch_poster.py
tests/test_courses_mapper.py
tests/test_holdings_csv_transformer.py
tests/test_mapper_base.py
tests/test_mapping_file_mapper_base.py
tests/test_organization_mapper.py
tests/test_organization_transformer.py
tests/test_rules_mapper_bibs_no_folio.py

https://github.com/FOLIO-FSE/folio_migration_tools/issues/509
- There is one single error message for invalid enum values:
```
raise TransformationRecordFailedError(
index_or_id,
f"Forbidden value for enum property {mapped_schema_property_name}."
f"Allowed values are: {mapped_schema_property['enum']}",
mapped_value,
)
```
- If a property is an enum and required, and the value is not "" and not in the list of allowed enum values -- raise TransformationRecordFailedError.
- If a property is an enum and not required, and the value is not "" and not in the list of allowed enum values  -- raise TransformationRecordFailedError.
- If a property is an enum and required, and the value is "" -- raise TransformationRecordFailedError.
- If a property is an enum and not required, and the value is "" -- …

509 mapper incorrectly fails record where a non required enum is empty

---

pyproject.toml
src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
src/folio_migration_tools/mapping_file_transformation/item_mapper.py
src/folio_migration_tools/mapping_file_transformation/order_mapper.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
tests/test_rules_mapper_base.py
tests/test_rules_mapper_bibs.py

Re-worked `item_mapper.get_prop()` to avoid unneeded calls to it's super(), replaced remaining `type() is` statements with `isinstance()` statements and updated tests to match. Also added some additional dev dependencies for mypy types while I was in there.

569 improve performance for itemstransformer by calling superget prop only when needed

---

pyproject.toml
src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
tests/test_rules_mapper_holdings.py

@branchedelac @fontanka16 Please take a look at this. As I've already merged the backwards-incompatible changes to the library configurations, I can go ahead and merge this to main and then use the branch to create a new 1.7.10 release.

Removing hrid from folio_holdings if create_source_records=False

---

src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
src/folio_migration_tools/migration_tasks/user_transformer.py
tests/test_mapping_file_mapper_base.py
tests/test_user_mapper.py
tests/test_user_transformer.py

**Fixes**
- Users: instead of crashing when an address does not have the isPrimary property, makes sure that all addresses have the isPrimary property and that foe exactly one address per user isPrimary == True, the rest False. #620
- Generic mapping: make replaceValues performs correct replacement when the value to replace _with_ is boolean False #504
- Generic mapping: alight reorganization of tests related to booleans #504
I think we can close #504 as the tests in mapping_file_mapper_base should cover all mappers using ().get_prop, which at this point should be all mappers. If we discover that something specific doesn't work we can add a test for that.

620 error when transforming users with addresses close #620 #504

---

src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
tests/test_mapping_file_mapper_base.py
tests/test_organization_mapper.py

This is pretty neat! It lets you, for example, have source data that looks like this
```
data = {
"name": "The Vendor",
"contact_person_l": "Janeway",
"contact_categories": "mspt^-^sls",
}
```
and a mapping like this
```
{
"folio_field": "contacts[0].categories[0]",
"legacy_field": "contact_categories",
"value": "",
"rules": {
"replaceValues": {
"mspt": "e193b0d1-4674-4a9e-818b-375f013d963f",
"sls": "604c2c9d-ed3a-46cd-bec4-69926c303b22",
}
},
"description": "",
},
```
to get a result like this
`'categories': ['e193b0d1-4674-4a9e-818b-375f013d963f', '604c2c9d-ed3a-46cd-bec4-69926c303b22']
`

542 make mapping file mapper base split value by subfield delimiter before applying replacevalues rule close #542

---

src/folio_migration_tools/mapping_file_transformation/notes_mapper.py
src/folio_migration_tools/mapping_file_transformation/order_mapper.py
src/folio_migration_tools/migration_tasks/orders_transformer.py
src/folio_migration_tools/migration_tasks/organization_transformer.py
src/folio_migration_tools/report_blurbs.py
src/folio_migration_tools/test_infrastructure/mocked_classes.py
tests/test_orders_mapper.py

**Organizations**
The organizations transformer now creates an organizayions_id_map 
**Orders**
Linking to FOLIO organizations and linking to FOLIO instances has been moved out of the get_prop method and into a "perform additional mapping". The main purpose of this was to circumvent problems (repeated lookups, incorrect reports) caused by https://github.com/FOLIO-FSE/folio_migration_tools/issues/628
Instead of fetching all organizations form FOLIO and using that as an ID map, the Order mapper now
1. Looks up the organization identifier in the organizaitons_id_map
2. If it doesn't find the identifier in the map, looks the identifier up (as property "Code") in FOLIO
3. If it still doesn't find an organization, the order fails

634 orders alternative implementation fetch and cache vendors only when needed close #634 close #635

---

.github/workflows/python-app.yml
src/folio_migration_tools/migration_tasks/loans_migrator.py

Closes #500 
This adds a check for either the lack of any `/smtp-configuration` records OR the presence of the string `"disabled"` in the `index 0` SMTP configuration's host parameter in Nolana or newer system. If present, SMTP is considered disabled by the system and the the `LoansMigrator` task will continue without pausing for 10 seconds.

Updating smtp check in loans migrator and bumping codecov action version

---

src/folio_migration_tools/marc_rules_transformation/conditions.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
tests/test_conditions.py
tests/test_holdings_statementsparser.py
tests/test_rules_mapper_holdings.py

Fix for failed contributor type text mapping when no ref data map is found, and some formatting fixes. 
Added missing `return` statement in `set_contributor_type_text` condition and added a test. I also changed the handling when there is no ref data match for `$4` or `$e` to use the `value` passed into the condition, rather than hard-coding to the first `$j` or `$e`
Fixes #647

Contributor type text mapping and source=FOLIO holdings hrid handling fixes

---

src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
tests/test_rules_mapper_bibs.py

Switched to dict() from set() to manage language code mappings and cleaned up tests to not invoke the mapping twice.

Implement #661 Preserve language code order when mapping 041/008 language codes

---

src/folio_migration_tools/__main__.py
tests/test_main.py

Revolves #683
If we still want prompting behavior with env var defaults, we could consider a separate env var for that - PromptParser has an env var it respects to disable prompts.
Also, I'm not sure of the right place in the documentation for this.

Environment variable defaults

---

src/folio_migration_tools/__main__.py
tests/test_main.py

If both
* FOLIO_MIGRATION_TOOLS_TASK_NAME env var is **unset**
* FOLIO_MIGRATION_TOOLS_CONFIGURATION PATH is **set**
Currently, the tool assigns the first positional arg to the config path, and chokes on no task name.
I propose in this that instead, we should just allow it to parse the arg as a task name.
This does mean that 
```bash
python -m folio_migration_tools arg
```
Will assign ```arg``` to config_path in *other* circumstances, and to task_name only in this situation - a bit ambiguous - but I still feel this is the closest to desired behavior

Allow Task Name as only positional param when config env var

---

src/folio_migration_tools/library_configuration.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_authorities.py
tests/test_rules_mapper_auth.py

Closes #693 and adds support for poppy-sunflower to FolioRelease class.

Fixes Authority JSON spec refactored in version 27 of `mod-inventory-storage

---

.github/workflows/python-app.yml

Checkout V2 and Setup Python V2 are depreciating.
For our purposes, Checkout V3 and Setup Python V4 are compatible without issue - so let's just bump the versions.

Update github action dependencies

---

pyproject.toml
src/folio_migration_tools/__main__.py
src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
tests/test_rules_mapper_bibs_no_folio.py

Bump to 1.8.4 and update dependencies

---

src/folio_migration_tools/circulation_helper.py
src/folio_migration_tools/migration_tasks/loans_migrator.py
src/folio_migration_tools/transaction_migration/legacy_loan.py
tests/test_loans_migrator.py

Adds support for a new `proxy_patron_barcode` column in the legacy loans data file, validates that barcode against transformed patron data, if present, and adds it to the `check-out-by-barcode` JSON object as `"proxyUserBarcode"`.
Closes #709

Added support for proxy borrowers to loans migrator task

---

src/folio_migration_tools/library_configuration.py
src/folio_migration_tools/migration_tasks/migration_task_base.py
src/folio_migration_tools/task_configuration.py

This change allows specification of an ECS data tenant ID to use in place of the the `tenantId` value specified in the`libraryInformation` section of the project configuration. This allows projects to contain tasks targeting different data tenants in an ECS-enabled system (eg. transform a set of shared MARC bibs against the central tenant, but transform a set of holdings and item records against separate member tenants per task). The `tenantId` value is used if no `ecsTenantId` is specified and is always used when initially authenticating to FOLIO.

Introducing ecs tenant id handling 

---

src/folio_migration_tools/marc_rules_transformation/holdings_statementsparser.py

Fixing dedupe_list_of_dict method on HoldingsStatementsParser does not preserve item order 

---

src/folio_migration_tools/marc_rules_transformation/holdings_statementsparser.py

Fixes holdings_statementparser should use dict.get with defaults instead of field[key] or "" 

---

src/folio_migration_tools/marc_rules_transformation/conditions.py
tests/test_conditions.py

Fix for staff-only note mapping rules in MARC bib 5xx fields not honored by migration tools

---

src/folio_migration_tools/mapping_file_transformation/item_mapper.py
tests/test_items_mapper.py

Update item_mapper to perform case-insensitive duplicate barcode detection for items

---

src/folio_migration_tools/migration_tasks/user_transformer.py
tests/test_user_transformer.py

Fixes UserTransformer creates invalid address objects #769 (with tests)

---

pyproject.toml
src/folio_migration_tools/migration_tasks/bibs_transformer.py
src/folio_migration_tools/migration_tasks/courses_migrator.py
src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
src/folio_migration_tools/migration_tasks/items_transformer.py
src/folio_migration_tools/migration_tasks/loans_migrator.py
src/folio_migration_tools/migration_tasks/manual_fee_fines_transformer.py
src/folio_migration_tools/migration_tasks/orders_transformer.py
src/folio_migration_tools/migration_tasks/organization_transformer.py
src/folio_migration_tools/migration_tasks/requests_migrator.py
src/folio_migration_tools/migration_tasks/reserves_migrator.py
src/folio_migration_tools/migration_tasks/user_transformer.py

1.8.17 release broke all migrationt tasks. This fixes it and does a superceding release.

Fix-task-inits-1817

---

src/folio_migration_tools/migration_tasks/batch_poster.py

Fix a bug introduced in #833 around writing all remaining records out to the failed records file when an exception occurs during a BatchPoster task.
The original implementation missed constructing a valid path object for the remaining file definitions. This change fixes that.
- Minor change to existing functionality to fix a bug

Fix file path references in failed records clean-up

---

src/folio_migration_tools/migration_tasks/batch_poster.py
src/folio_migration_tools/task_configuration.py

Fixes [#578](https://github.com/FOLIO-FSE/folio_migration_tools/issues/578)
Annotations to the Task configuration entries for BatchPoster has been added
This just needs approval
```bash
cd tests
pytest test_batch_poster.py
```

578 Add annotation to the Task configuration entries for BatchPoster

---

tests/test_conditions.py

Fixes [#346](https://github.com/FOLIO-FSE/folio_migration_tools/issues/346)
Added two test cases for the condition_remove_prefix_by_indicator method to check marc_field.indicator2 in the range of 1-9 and outside of this range.
Unfortunately, I was unable to complete all the conditions in the check list below because `nox -rs safety` is causing an error `poetry: The requested command export does not exist.`, and `nox -rs tests` with tenant and credentials is causing errors
```
ModuleNotFoundError: No module named 'tzdata'
zoneinfo._common.ZoneInfoNotFoundError: 'No time zone found with key UTC'. 
```
However, running the test separately with `pytest test_conditions.py` does not result in errors in the written code, so I hope the task of writing the test itself to be completed.
```bash
cd …
```

346 Two test cases for condition_remove_prefix_by_indicator

---

src/folio_migration_tools/migration_tasks/courses_migrator.py

Fixes [#580](https://github.com/FOLIO-FSE/folio_migration_tools/issues/580)
Annotations for the Task configuration entries for CoursesMigrator has been added
This just needs approval
```bash
cd tests
pytest test_batch_poster.py
```

580 Add annotation to the Task configuration entries for CoursesMigrator

---

src/folio_migration_tools/migration_tasks/user_transformer.py

Fixes [#589](https://github.com/FOLIO-FSE/folio_migration_tools/issues/589)
- Annotations to the Task configuration entries for UserTransformer has been added
- Some typos fixed
- Minor canges. This just needs approval
```bash
poetry run pytest tests/test_user_transformer.py
```

589 Add annotations to the Task configuration entries for UserTransformer

---

src/folio_migration_tools/migration_tasks/reserves_migrator.py

Fixes [#588](https://github.com/FOLIO-FSE/folio_migration_tools/issues/588)
Annotations to the Task configuration entries for ReservesMigrator has been added
- Minor changes. This just needs approval.
```bush
poetry run pytest tests/test_reserves_migrator.py
```

588 Add annotations to the Task configuration entries for ReservesMigrator

---

src/folio_migration_tools/migration_tasks/requests_migrator.py

Fixes [#587](https://github.com/FOLIO-FSE/folio_migration_tools/issues/587)
Annotations to the Task configuration entries for RequestMigrator has been added.
- Minor changes, this just needs approval
```bash
poetry run pytest tests/test_requests_migrator.py
```

587 Add annotations to the Task configuration entries for RequestsMigrator

---

pyproject.toml

`nox -rs safety` doesn't run without installing export plugin for poetry.
Command for installing export plugin has beed added to pyproject.toml.
- Minor change, needs approval
Clear install poetry then run `nox -rs safety`

Poetry export plugin has been added to pyproject.toml

---

src/folio_migration_tools/migration_tasks/orders_transformer.py

Fixes [#585](https://github.com/FOLIO-FSE/folio_migration_tools/issues/585)
Annotations to the Task configuration entries for OrdersTransformer has been added.
```bash
cd tests; poetry run pytest ./tests/test_orders_transformer.py
```

585 Add annotations to the Task configuration entries for OrdersTransformer

---

src/folio_migration_tools/migration_tasks/loans_migrator.py

Fixes [#584](https://github.com/FOLIO-FSE/folio_migration_tools/issues/584)
Annotations to the Task configuration entries for LoansMigrator has been added.
```bash
poetry run pytest ./tests/test_loans_migrator.py
```

584 Add annotations to the Task configuration entries for LoansMigrator

---

src/folio_migration_tools/migration_tasks/items_transformer.py

Fixes [#583](https://github.com/FOLIO-FSE/folio_migration_tools/issues/583)
Annotations to the Task configuration entries for ItemsTransformer has been added
```bash
poetry run pytest ./tests/test_items_transformer.py
```

583 Add annotations to the Task configuration entries for ItemsTransformer

---

src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py

Fixes [#581](https://github.com/FOLIO-FSE/folio_migration_tools/issues/581) 
Annotations to the Task configuration entries for HoldingsCsvTransformer have been added
```bash
poetry run pytest ./tests/test_holdings_csv_transformer.py
```

581 Add annotations to the Task configuration entries for HoldingsCsvTransformer

---

src/folio_migration_tools/transaction_migration/legacy_loan.py
tests/test_legacy_loan.py

Fixes [#713](https://github.com/FOLIO-FSE/folio_migration_tools/issues/713)
Added a new function set_renewal_count(loan: dict) that returns 0 if the key "renewal_count" is missing in the loan dictionary, or its value is empty or not a string containing a number, otherwise it returns an integer from its value. Corresponding test cases have been added.
This just needs approval.
Migrate loans with missing, empty or unresolvable values of renewal count.

713 loans migrator empty renewal count issue

---

src/folio_migration_tools/transaction_migration/legacy_reserve.py
tests/test_legacy_reserve.py

Fixes [#349](https://github.com/FOLIO-FSE/folio_migration_tools/issues/349)
Tests for legacy_reserve.py have been added. Minor error in passing parameters for TransformationProcessError fixed.
```bash
poetry run pytest -v tests/test_legacy_reserve.py
```

349 Increase test coverage in legacy_reserve.py (rebased)

---

src/folio_migration_tools/mapping_file_transformation/order_mapper.py
tests/test_orders_mapper.py

Refactoring to fulfill @bltravis [comment](https://github.com/FOLIO-FSE/folio_migration_tools/pull/825#pullrequestreview-2612562784) to [PR](https://github.com/FOLIO-FSE/folio_migration_tools/pull/825).
Global variable has been deleted new static function `is_valid_po_number()` and test for it have been added.
```bash
poetry run pytest ./tests/test_orders_mapper.py
```

Refactoring validate_po_number method in order_mapper

---

src/folio_migration_tools/migration_tasks/items_transformer.py
tests/test_items_transformer.py

Partially fixes [#872](https://github.com/FOLIO-FSE/folio_migration_tools/issues/872)
Added tests for load_boundwith_relationships, some refactor
```bash
poetry run pytest -v ./tests/test_items_transformer.py
```

872 increase test coverage for items transformer

---

tests/test_user_transformer.py

Fixes [#873](https://github.com/FOLIO-FSE/folio_migration_tools/issues/873)
Added unit tests for:
* remove_empty_addresses
* find_primary_addresses
```bash
poetry run pytest -v ./tests/test_user_transformer.py
```

873 Increase test coverage for user_transformer

---

src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
src/folio_migration_tools/task_configuration.py
tests/test_holdings_marc_transformer.py

Fixes [#870](https://github.com/FOLIO-FSE/folio_migration_tools/issues/870)
- refactored typos, long lines and some variables defenition
- add some tests
```bash
poetry run pytest -v ./tests/test_holdings_marc_transformer.py
```

870 Increase test coverage for holdings_marc_transformer
