- marc_to_folio/default_mapper.py
Hey Theodor!
I added more instance type key/value pairs to the instance_types table
> Added to the instance-types table.

- src/folio_migration_tools/holdings_helper.py
- src/folio_migration_tools/migration_tasks/batch_poster.py
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- tests/test_holdings_csv_transformer.py
Also, fix path issue when reposting failed records for Batch Poster
> add test and documentation for bw merges

- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
> Updates unique_001s set assignment

- setup.cfg
- tests/test_user_transformer.py
Please look into the extensive comments at https://github.com/FOLIO-FSE/folio_migration_tools/issues/265
> User booleans

- src/folio_migration_tools/migration_tasks/bibs_transformer.py
I moved the context manager for the failed_bibs_file into the `do_work` method of the transformer class. It's now passed into the `read_records` method rather than being instantiated there. Tested against records supplied by @branchedelac (three records split across two files) and all three are written to the file successfully.
> Fix for issue #252

- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/holdings_processor.py
- src/folio_migration_tools/migration_report.py
- src/folio_migration_tools/migration_tasks/batch_poster.py
- src/folio_migration_tools/migration_tasks/bibs_transformer.py
- src/folio_migration_tools/migration_tasks/courses_migrator.py
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- src/folio_migration_tools/migration_tasks/items_transformer.py
- src/folio_migration_tools/migration_tasks/loans_migrator.py
- src/folio_migration_tools/migration_tasks/migration_task_base.py
- src/folio_migration_tools/migration_tasks/requests_migrator.py
- src/folio_migration_tools/migration_tasks/reserves_migrator.py
- src/folio_migration_tools/migration_tasks/user_transformer.py
- tests/test_migration_report.py
@bltravis @branchedelac  Anyone want to check? There are three fixed issues here, mentioned in the commit messages. Please assign yourself if you take it on.
> 264 add time duration for migration task to migration reports

- src/folio_migration_tools/library_configuration.py
- src/folio_migration_tools/migration_tasks/loans_migrator.py
- src/folio_migration_tools/migration_tasks/requests_migrator.py
- src/folio_migration_tools/transaction_migration/legacy_loan.py
- src/folio_migration_tools/transaction_migration/legacy_request.py
- tests/test_legacy_loan.py
- tests/test_legacy_request.py
- tests/test_loans_migrator.py
This adds multiple options:
- Use a fallback service point id for all loans files (previous functionality)
- Use a fallback service point id for each loan file 
- Add a service_point_id column to your loans file(s)
> closes #303

- src/folio_migration_tools/library_configuration.py
- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/holdings_processor.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
- src/folio_migration_tools/migration_tasks/bibs_transformer.py
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
- src/folio_migration_tools/migration_tasks/items_transformer.py
- src/folio_migration_tools/test_infrastructure/mocked_classes.py
- tests/test_courses_mapper.py
- tests/test_holdings_csv_transformer.py
- tests/test_mapping_file_mapper_base.py
- tests/test_mapping_file_mapping_base_impl.py
- tests/test_rules_mapper_bibs.py
- tests/test_user_transformer.py
These four should all be done as of this PR:
https://github.com/FOLIO-FSE/folio_migration_tools/milestone/9
> Improvements in HRID handling

- tests/test_holdings_processor.py
> Adding tests for generate_num_part method

- src/folio_migration_tools/helper.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/test_infrastructure/mocked_classes.py
- tests/test_data/default/test4.xml
- tests/test_helper.py
- tests/test_rules_mapper_bibs.py
I looked at some of the code analysis on the train back from Hamburg and this instance id piece was quite a mouthful, so I started dividing the method into smaller pieces and adding some test coverage.
> Refactor and increase test coverage in rules-mapper-bibs

- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- tests/test_mapping_file_mapper_base.py
Here's my take on implementing #339. I still need to write tests, so we can hold off on merging for now, but I wanted to get some additional eyes on it.
> Add support for counting and logging/reporting rows in delimited source data files

- src/folio_migration_tools/mapping_file_transformation/courses_mapper.py
- src/folio_migration_tools/migration_tasks/courses_migrator.py
- src/folio_migration_tools/test_infrastructure/mocked_classes.py
- tests/test_courses_mapper.py
- tests/test_mapping_file_mapper_base.py
> Fetch Instructor information from Users

- docs/index.md
- docs/mapping_files.md
- docs/migration_process.md
- docs/migration_tasks.md
- tests/test_ref_data_mappings.py
> 411 implementidentify solution for correctly mapping categories to multiple objects in the same array

- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/hrid_handler.py
- src/folio_migration_tools/marc_rules_transformation/marc_file_processor.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
- src/folio_migration_tools/migration_tasks/bibs_transformer.py
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
- src/folio_migration_tools/migration_tasks/items_transformer.py
- tests/test_data/diacritics/diac_from_oclc.mrc:Zone.Identifier
- tests/test_holdings_processor.py
Test coverage is...not ideal. But it does not crash.
> clean up HRID handling

- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- tests/test_mapping_file_mapper_base.py
At this stage, I decided to only handle the defaults on the first level.
> Handle schema enums and default properties

- src/folio_migration_tools/library_configuration.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/migration_tasks/bibs_transformer.py
> Adding custom ilsFlavour option with field+subfield specification in task definition

- src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- tests/test_helper.py
- tests/test_items_mapper.py
- tests/test_loans_migrator.py
- tests/test_orders_transformer.py
- tests/test_organization_transformer.py
- Implemented this suggestion
- Added basic test for item mapper
> 543 include legacy values mapped to array subproperties in mapped legacy fields close #543 #79 #84

- generated_schemas/HoldingsMarcTransformerSchema.json
- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/mapping_file_transformation/item_mapper.py
- src/folio_migration_tools/marc_rules_transformation/marc_file_processor.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_authorities.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
- src/folio_migration_tools/migration_tasks/items_transformer.py
- tests/test_holdings_csv_transformer.py
- tests/test_mapper_base.py
- tests/test_rules_mapper_auth.py
- tests/test_rules_mapper_bibs.py
- tests/test_rules_mapper_bibs_no_folio.py
- tests/test_rules_mapper_holdings.py
> 380 implement bound with mapping for voyager

- src/folio_migration_tools/mapping_file_transformation/order_mapper.py
- src/folio_migration_tools/report_blurbs.py
- tests/test_orders_mapper.py
An initial implementation for PoL location mapping. @branchedelac, please review. Will cherry-pick this into the 1.7.x branch and go ahead and do another release there.
> Initial mapping for PoL locationId

- src/folio_migration_tools/custom_exceptions.py
- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/mapping_file_transformation/manual_fee_fines_mapper.py
- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- src/folio_migration_tools/migration_tasks/manual_fee_fines_transformer.py
- src/folio_migration_tools/migration_tasks/migration_task_base.py
- src/folio_migration_tools/test_infrastructure/mocked_classes.py
- tests/test_manual_fee_fines_mapper.py
- tests/test_migration_task_base.py
Closes #619 and #618, plus improves error and bad data handling/reporting.
> 619 feesfines adjust actiondate to reflect local tenant timezone close #619 #618

- pyproject.toml
- src/fetch_default_ref_data.py
- src/folio_migration_tools/__main__.py
- src/folio_migration_tools/circulation_helper.py
- src/folio_migration_tools/mapping_file_transformation/order_mapper.py
- src/folio_migration_tools/mapping_file_transformation/organization_mapper.py
- src/folio_migration_tools/marc_rules_transformation/hrid_handler.py
- src/folio_migration_tools/marc_rules_transformation/marc_file_processor.py
- src/folio_migration_tools/migration_tasks/batch_poster.py
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- src/folio_migration_tools/migration_tasks/loans_migrator.py
- src/folio_migration_tools/migration_tasks/reserves_migrator.py
Swaps out requests library for httpx, and switches to httpx.Client instances for BatchPoster, rather than creating a new http connection for each post.
Closes #553
> 553 replace the current use of requests with something that is faster and more modern

- src/folio_migration_tools/holdings_helper.py
- src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
- src/folio_migration_tools/mapping_file_transformation/item_mapper.py
- src/folio_migration_tools/migration_tasks/items_transformer.py
- tests/test_holdings_mapper.py
- tests/test_items_mapper.py
> 639 implement discoverysuppress from file definition for delimited holdings and items

- src/folio_migration_tools/marc_rules_transformation/hrid_handler.py
> Removing failure points for hrid prefix settings being empty

- src/folio_migration_tools/marc_rules_transformation/conditions.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
- tests/test_rules_mapper_bibs.py
Fixes #655
Not sure about the elegance of my implementation here. Needed to adjust the tests to get them to pass (not sure the MARC record being used to test the subjects mapping really fits with the FOLIO default mapping).
@jermnelson, would love to get your team's eyes on this, especially if this is something you'd like to have for your migration.
> Initial implementation of handling for subFieldDelimiter in MARC rules mapper

- src/folio_migration_tools/marc_rules_transformation/hrid_handler.py
- tests/test_basic.py
> 679 remove 003 when converting 001 to 035 during instance transformation

- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_authorities.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
- src/folio_migration_tools/migration_tasks/user_transformer.py
- tests/test_rules_mapper_base.py
- tests/test_user_transformer.py
> Implement #697: Do not add metadata objects to generated records

- src/folio_migration_tools/marc_rules_transformation/conditions.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_authorities.py
- tests/test_conditions.py
> Added trim_punctuation condition function and some clean-up

- src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
- tests/test_rules_mapper_bibs_no_folio.py
> Handle subfield 9 in source MARC authorizable field mapping

- src/folio_migration_tools/mapping_file_transformation/user_mapper.py
- src/folio_migration_tools/migration_tasks/user_transformer.py
- tests/test_user_mapper.py
Created the option with a default of false.
> Created remove_request_preferences parameter to User transform task

- src/folio_migration_tools/migration_tasks/batch_poster.py
- src/folio_migration_tools/migration_tasks/loans_migrator.py
> Tweaking how the httpx client works in batchposter to fix a token expiration issue

- pyproject.toml
> Bumping version to 1.8.5 for release

- CHANGELOG.md
- src/folio_migration_tools/migration_tasks/orders_transformer.py
Changed OrderTransformer.TaskConfiguration to inherit from AbstractTaskBaseClass instead of BaseClass
> 1.8.6 changelog and fix for #735

- CHANGELOG.md
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
> Fix for MARC Holdings Transformer Fails During wrap-up #742 

- src/folio_migration_tools/mapper_base.py
- tests/test_mapper_base.py
> Fix for Handle call numbers containing square brackets "[]" #754

- .gitignore
- CHANGELOG.md
- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
- tests/test_holdings_csv_transformer.py
> Fixes III-style bound with fixes for multiple holdings with the same linked bibIds

- src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
- tests/test_holdings_mapper.py
> Extract relevant value from single-item "bib call number" lists (eg. III items with boundwiths) in holdings_mapper.get_call_number

- src/folio_migration_tools/migration_tasks/holdings_csv_transformer.py
> Wiring in perform_additional_mappings method call to post_process_holding method in csv holdings migration task

- src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
> Added a check for title in the preceding-succeeding-title entity, creating a data issue log event if not present

- src/folio_migration_tools/mapper_base.py
- tests/test_mapper_base.py
> Fixes Handle single-item list of call numbers for III-style bound with items #768

- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- src/folio_migration_tools/mapping_file_transformation/user_mapper.py
- tests/test_user_mapper.py
* Removed `type` from list of fields to ignore
* Fixed `preferredContactTypeId` value ("Email" to "email")
* Updated tests
Closes #779
> Fixes #779 and changing preferredContactTypeId mapping to valid value

- src/folio_migration_tools/marc_rules_transformation/rules_mapper_base.py
- src/folio_migration_tools/migration_tasks/batch_poster.py
- tests/test_batch_poster.py
- tests/test_rules_mapper_base.py
Also made some tweaks to clean-up Flake8 errors.
> Adding some tests for BatchPoster and rules_mapper_base. 

- pyproject.toml
- src/folio_migration_tools/migration_tasks/batch_poster.py
- tests/test_batch_poster.py
> 799 batchposter for extradata broken in 1814

- pyproject.toml
> Bump folioclient to 0.61.0 and bump verstion to 1.8.16

- CONTRIBUTING.md
- pyproject.toml
- src/fetch_default_ref_data.py
- src/folio_migration_tools/__main__.py
- src/folio_migration_tools/mapping_file_transformation/mapping_file_mapper_base.py
- src/folio_migration_tools/mapping_file_transformation/order_mapper.py
- src/folio_migration_tools/mapping_file_transformation/organization_mapper.py
- src/folio_migration_tools/migration_tasks/batch_poster.py
- src/folio_migration_tools/migration_tasks/migration_task_base.py
- tests/test_main.py
> Set httpx logger level to WARNING to avoid unneeded log messages and add upsert support to inventory batchposters

- pyproject.toml
- src/folio_migration_tools/migration_tasks/batch_poster.py
> Add folio_client to BatchPoster __init__ and super().__init__

- pyproject.toml
- src/folio_migration_tools/mapping_file_transformation/item_mapper.py
- src/folio_migration_tools/migration_tasks/items_transformer.py
- tests/test_items_mapper.py
Fixes #837 
Adds task configuration as an argument for ItemsMapper.__init__() and adds tests for ItemsMapper.get_prop to test mapping behavior.
> Fix optional item permanent location map implementation

- .github/workflows/python-publish.yml
- pyproject.toml
- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
Fixing call number mapping issue reported by @marnold-ebsco for 1.8.x release branch.
- No approval needed
Transform the failing dataset.
> Fix get call number square brackets

- src/folio_migration_tools/mapping_file_transformation/holdings_mapper.py
Add additional exception handling for ValueError in get_call_number of the HoldingsMapper
Add ValueError to except statement in `HoldingsMapper.get_call_number`
- Minor change, already in 1.8.x branch and released in 1.8.20
> get_call_number fix to handle valueerror

- src/folio_migration_tools/migration_tasks/organization_transformer.py
Fixes [#586](https://github.com/FOLIO-FSE/folio_migration_tools/issues/586)
Annotations to the Task configuration entries for OrganizationTransformer has been added
```bash
poetry run pytest tests/test_organization_transformer.py
```
> 586 Add annotations to the Task configuration entries for OrganizationTransformer

- pyproject.toml
- src/folio_migration_tools/mapping_file_transformation/order_mapper.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
- src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
- tests/test_rules_mapper_holdings.py
Add support for slipstreaming MFHD mapping rules and fix schema retrieval code for orders.
Update MFHD mapper task to accept a JSON file name and use that file to update the mapping rules retrieved from FOLIO. Also copy the MFHD 852 to a 952 to support mapping $x and $z as holdings notes.
> 843 support generating instance relationships parentchild during marc bib transformation

- src/folio_migration_tools/migration_tasks/migration_task_base.py
- tests/test_data/ref_data_maps/locations_map_empty.tsv
- tests/test_data/ref_data_maps/locations_map_too_many_columns.tsv
- tests/test_data/ref_data_maps/locations_map_valid.tsv
- tests/test_migration_task_base.py
Fixes #826 
* Add verify_ref_data_mapping_file_structure static method to Migration TaskBase
* Make load_ref_data_mapping_file a static method
* Add tests.
Please take a look at the logic and make sure it satisfies the stated requirements.
> Update MigrationTaskBase to support structural verification of reference data files (#826)

- src/folio_migration_tools/custom_exceptions.py
- src/folio_migration_tools/transaction_migration/legacy_loan.py
- tests/test_legacy_loan.py
Fixes [#350](https://github.com/FOLIO-FSE/folio_migration_tools/issues/350)
Test coverage has been increased and some minor refactoring has been performed.
- Please check correct_for_1_day_loans() and make your suggestion
- Typo in class name TransformationError in custom_exceptions.py has been fixed
```bash
poetry run pytest -vv ./tests/test_legacy_loan.py
```
> Test coverage in legacy_loan has been increased (#350)

- pyproject.toml
- src/folio_migration_tools/migration_tasks/loans_migrator.py
- src/folio_migration_tools/migration_tasks/user_transformer.py
Closes Switch to python-art for ascii art (eg. SMTP?, E-mail?) #880
* Remove custom ASCII art from loans migrator and user transformer
* Added dependency on python-art module
* Replace custom ASCII art with `tprint()` calls
Just needs approval
> Remove custom ASCII art and replace with art module

- src/folio_migration_tools/migration_tasks/items_transformer.py
Fixes #868
Replaced the old folder_structure path object with the new-style path sytax that uses the file specified in the task configuration.
> Fix temporary loan type mapping file path reference in ItemsTransformer to use specified instead of fixed path.

- src/folio_migration_tools/mapping_file_transformation/user_mapper.py
- tests/test_user_mapper.py
Closes #822
Change ref data mapping to prevent default department mapping.
> Change get_mapped_name arguments for departments_mapping to prevent_default=True.

- pyproject.toml
Bump dev dependencies to fix test failures in Python3.13
> bump lxml dev dependency

- pyproject.toml
- src/folio_migration_tools/migration_tasks/migration_task_base.py
Fix unbound local error and set new RC version
> Fix-unbound-local-error-in-1.9.0rc8

- pyproject.toml
> Bump Version to 1.9.0rc10

- pyproject.toml
- src/folio_migration_tools/__main__.py
- src/folio_migration_tools/circulation_helper.py
- src/folio_migration_tools/library_configuration.py
- src/folio_migration_tools/mapper_base.py
- src/folio_migration_tools/marc_rules_transformation/hrid_handler.py
- src/folio_migration_tools/migration_tasks/batch_poster.py
- src/folio_migration_tools/migration_tasks/loans_migrator.py
- src/folio_migration_tools/migration_tasks/reserves_migrator.py
- src/folio_migration_tools/transaction_migration/legacy_reserve.py
- tests/test_batch_poster.py
- tests/test_holdings_csv_transformer.py
- tests/test_loans_migrator.py
- tests/test_main.py
- tests/test_mfhd_rules_mapper.py_legacy
- tests/test_rules_mapper_auth.py
- tests/test_rules_mapper_base.py
- tests/test_rules_mapper_bibs.py
- tests/test_rules_mapper_bibs_no_folio.py
- tests/test_rules_mapper_holdings.py
Bump folioclient version to 0.70.1 to take advantage of changes to http error handling, update arguments and configuration parameters to reflect changing nomenclature in FOLIO, and add ability to print version when executing as a script.
* Bump folioclient version to 0.70.1
* Update arguments to __main__.py to reflect changes from folioclient (change `okapi_url` to `gateway_url`, etc.)
* Add `--version` and `-V` arguments to __main__.py and print the module version
* Bump RC version to 1.9.0rc11
> Bump folioclient to 0.70.1, update references to okapi_url to gateway_url and related changes, add option to print version when calling as a script

- .readthedocs.yml
- docs/conf.py
- docs/installing.md
- docs/mapping_file_based_mapping.md
- docs/mapping_files.md
- docs/migration_process.md
- docs/migration_tasks.md
- docs/quick_tutorial.md
Update docs and fix automatic docs build.
Updated docs files to reflect changes made for 1.9.0+
> 884-update-docs-for-190

- src/folio_migration_tools/transaction_migration/legacy_loan.py
- tests/test_legacy_loan.py
Fixes #908
Tweaks to LegacyLoan class
> Refactor LegacyLoan to use instance variable for legacy_loan_dict and enhance error reporting for missing date information. Update tests.

- pyproject.toml
- src/folio_migration_tools/__main__.py
- src/folio_migration_tools/mapping_file_transformation/organization_mapper.py
- src/folio_migration_tools/marc_rules_transformation/holdings_statementsparser.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_bibs.py
- src/folio_migration_tools/marc_rules_transformation/rules_mapper_holdings.py
- src/folio_migration_tools/migration_tasks/holdings_marc_transformer.py
- src/folio_migration_tools/transaction_migration/legacy_loan.py
- src/folio_migration_tools/translations/en.json
- tests/test_holdings_statementsparser.py
- tests/test_legacy_loan.py
- tests/test_rules_mapper_bibs.py
Closes #912, #913, #914
Also update tests and make a small change to __main__.py prevent swallowing exceptions during task init.
* Check for empty list of 1xx/7xx fields before trying to map one
* Add check for proper configuration before trying to perform note mapping for 85x/86x fields to mrc/mrk
* Add/update tests to cover changes in this PR and the previous
* Move the sys.exit call from withing the try-except block where tasks are executed in __main__.main() to the end of the function, so that it's not swallowing un-caught task-level exceptions (should improve diagnosing problems during task init)
> 912-simple_bib_map-fails-when-no-1xx-or-7xx-is-present-in-the-bib-record

- src/folio_migration_tools/migration_tasks/batch_poster.py
- tests/test_batch_poster.py
Fixes [#874](https://github.com/FOLIO-FSE/folio_migration_tools/issues/874)
- refactored typos, long lines and some variables defenition
- fixed source for testing modules in test_batch_poster.py
- increased test coverage for some methods of BatchPoster
```bash
python -m pytest -v ./tests/test_batch_poster.py
```
> 874 increase test coverage for batch_poster and improve code formatting

- docs/migration_tasks.md
- src/folio_migration_tools/mapping_file_transformation/user_mapper.py
- src/folio_migration_tools/test_infrastructure/mocked_classes.py
- tests/test_user_mapper.py
> Implement fix for Support mapping multiple departments using multi_field_delimiter

- pyproject.toml
- src/folio_migration_tools/circulation_helper.py
- src/folio_migration_tools/helper.py
- src/folio_migration_tools/migration_tasks/loans_migrator.py
- src/folio_migration_tools/transaction_migration/legacy_loan.py
- tests/test_helper.py
- tests/test_legacy_loan.py
- tests/test_loans_migrator.py
Enhance the handling of checked out items in the loans poster and update the version to 1.9.5.
Enhance the handling of checked out items in the loans poster and update the version to 1.9.5.
> Update loan handling and version bump to 1.9.5
